package com.soap.calculator.api.calculations;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-06-13T18:02:02.804+05:30
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://www.soap.com/calculator/api/calculations", name = "CalculationIndicator")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CalculationIndicator {

    @WebMethod(operationName = "Calculation")
    @WebResult(name = "CalculationResponse", targetNamespace = "http://www.soap.com/calculator/api/calculations", partName = "CalculationResponse")
    public CalculationResponse calculation(

        @WebParam(partName = "CalculationRequest", name = "CalculationRequest", targetNamespace = "http://www.soap.com/calculator/api/calculations")
        CalculationRequest calculationRequest
    );
}
