package com.soap.calculator.api.calculations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-06-13T18:02:02.829+05:30
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "CalculationIndicatorService",
                  wsdlLocation = "file:/C:/Users/seesuraj/Documents/Sapient/workspace/spring-boot-rest-calculator/src/main/resources/wsdl/calculator.wsdl",
                  targetNamespace = "http://www.soap.com/calculator/api/calculations")
public class CalculationIndicatorService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.soap.com/calculator/api/calculations", "CalculationIndicatorService");
    public final static QName CalculationIndicatorSoap11 = new QName("http://www.soap.com/calculator/api/calculations", "CalculationIndicatorSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/seesuraj/Documents/Sapient/workspace/spring-boot-rest-calculator/src/main/resources/wsdl/calculator.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculationIndicatorService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/seesuraj/Documents/Sapient/workspace/spring-boot-rest-calculator/src/main/resources/wsdl/calculator.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculationIndicatorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculationIndicatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculationIndicatorService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CalculationIndicatorService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculationIndicatorService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculationIndicatorService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CalculationIndicator
     */
    @WebEndpoint(name = "CalculationIndicatorSoap11")
    public CalculationIndicator getCalculationIndicatorSoap11() {
        return super.getPort(CalculationIndicatorSoap11, CalculationIndicator.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculationIndicator
     */
    @WebEndpoint(name = "CalculationIndicatorSoap11")
    public CalculationIndicator getCalculationIndicatorSoap11(WebServiceFeature... features) {
        return super.getPort(CalculationIndicatorSoap11, CalculationIndicator.class, features);
    }

}
