//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.13 at 11:20:20 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.soap.com/calculator/api/calculations")
package com.soap.calculator.api.calculations;
